modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
license = "${license}"
#issueTrackerURL = "https://change.me.to.your.issue.tracker.example.invalid/" #optional

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
#updateJSONURL = "https://change.me.example.invalid/updates.json"
#displayURL = "https://change.me.to.your.mods.homepage.example.invalid/"
logoFile = "${mod_id}.png"
credits = "${credits}"
authors = "${mod_author}"
description = '''${description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
